# Generated by Django 4.1.7 on 2023-04-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryap', '0003_category1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
