# Generated by Django 4.1.7 on 2023-04-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productap', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'variation_value')},
        ),
    ]
