# Generated by Django 4.1.7 on 2023-04-22 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productap', '0002_alter_productvariation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
