# Generated by Django 4.1.7 on 2023-04-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userap', '0004_address_mobile_number_address_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
