# Generated by Django 4.1.7 on 2023-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderap', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('COD', 'COD'), ('ONLINE_PAYMENT', 'ONLINE_PAYMENT'), ('paypal', 'paypal')], default='COD', max_length=200, null=True),
        ),
    ]
