# Generated by Django 4.1.7 on 2023-04-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderap', '0007_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address_json',
            new_name='shipping_address',
        ),
    ]
