# Generated by Django 4.1.7 on 2023-04-24 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderap', '0006_alter_order_payment_status'),
        ('sales', '0002_sales_delete_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='orderap.order'),
        ),
    ]
